services:
  server:
    image: ${IMAGE_NAME:-skyfunnel-email-queue}:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start:server"]
    network_mode: host  # Add this
    # Remove the ports section - not needed with host mode
    env_file:
      - .env
    environment:
      - PORT=3000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  worker:
    image: ${IMAGE_NAME:-skyfunnel-email-queue}:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start:worker"]
    env_file:
      - .env
    restart: always
    network_mode: host