services:
  server:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    command: ["npm", "run", "start:server"]
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  worker:
    image: ${IMAGE_NAME}:{IMAGE_TAG}
    command: ["npm", "run", "start:worker"]
    env_file:
      - .env
    restart: always
