services:
  server:
    build: .
    command: ["npm", "run", "start:server"]
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000

  worker:
    build: .
    command: ["npm", "run", "start:worker"]
    env_file:
      - .env