version: "3.9"

services:
  # Server: HTTP API, exposed normally
  server:
    image: ${IMAGE_NAME:-skyfunnel-email-queue}:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start:server"]
    ports:
      - "3000:3000"   # expose API to outside world
    env_file:
      - .env
    environment:
      - PORT=3000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Worker: needs host networking for SMTP/Redis
  worker:
    image: ${IMAGE_NAME:-skyfunnel-email-queue}:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start:worker"]
    env_file:
      - .env
    restart: always
    network_mode: host   # REQUIRED for SMTP bind to host IP
