name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
    deploy-dev:
        if: ${{ github.event.workflow_run.head_branch == 'dev' }}
        runs-on: [self-hosted, email-queue-dev]  # only runs on dev server
        env:
            IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        steps:
          - name: Log in to Docker Hub
            uses: docker/login-action@v2
            with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD_READ_ONLY }}

      # 3️⃣ Set image tag
          - name: Pull latest Docker image
            run: |
                echo "Pulling latest Docker image: $IMAGE_NAME:dev"
                docker pull $IMAGE_NAME:dev

          - name: Run reload.sh
            run: |
                chmod +x /home/actions/scripts/reload.sh
                /home/actions/scripts/reload.sh


    deploy-prod:
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        runs-on: [self-hosted, email-queue-prod]  # only runs on prod server
        env:
            IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        steps:
          - name: Log in to Docker Hub
            uses: docker/login-action@v2
            with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD_READ_ONLY }}

        # 3️⃣ Set image tag
          - name: Pull latest Docker image
            run: |
                echo "Pulling latest Docker image: $IMAGE_NAME:prod"
                docker pull $IMAGE_NAME:prod


          - name: Run reload.sh
            run: |
                   chmod +x /home/actions/scripts/reload.sh
                   /home/actions/scripts/reload.sh
