name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    env:
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
    steps:
    #login docker hub to pull image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD_READ_ONLY }}

      - name: Pull latest Docker image
        run: docker pull ${{ secrets.IMAGE_NAME }}:latest

      - name: Run reload.sh
        run: |
          chmod +x /home/actions/scripts/reload.sh
          /home/actions/scripts/reload.sh
