name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: self-hosted
    env:
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD_READ_ONLY }}

      # 3️⃣ Set image tag
      - name: Pull latest Docker image
        run: |
            BRANCH=${{ github.event.workflow_run.head_branch }}
            echo "BRANCH=$BRANCH"
            if [ "$BRANCH" = "main" ]; then
            TAG=prod
            elif [ "$BRANCH" = "dev" ]; then
            TAG=dev
            else
            TAG=$BRANCH
            fi
            echo "TAG=$TAG"
            docker pull $IMAGE_NAME:$TAG


      - name: Run reload.sh
        run: |
          chmod +x /home/actions/scripts/reload.sh
          /home/actions/scripts/reload.sh
